version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mzerek
      MONGO_INITDB_ROOT_PASSWORD: mzerek
      MONGO_INITDB_DATABASE: mzerek_db
    ports:
      - 27017:27017